"""Combine KiCad's bare-board GLB with the authored package-envelope VRML.

Build-only dependencies: trimesh 4.8.3, numpy 2.5.3. No source CAD is modified.
Only the Box/IndexedFaceSet subset generated by skylark_models.py is accepted.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import numpy as np
import trimesh

ROOT = Path(__file__).resolve().parents[2]


def models(text):
    for line in text.splitlines():
        if not line or line.startswith('#'): continue
        color = [float(v) for v in re.search(r'diffuseColor ([\d. ]+)', line)[1].split()]
        if 'geometry Box' in line:
            size = [float(v)*2.54 for v in re.search(r'size ([\d.eE+ -]+)', line)[1].split()]
            offset = [float(v)*2.54 for v in re.search(r'translation ([\d.eE+ -]+)', line)[1].split()]
            mesh = trimesh.creation.box(extents=size);mesh.apply_translation(offset)
        elif 'geometry IndexedFaceSet' in line:
            points = np.fromstring(re.search(r'point \[ (.*?) \]', line)[1].replace(',', ' '), sep=' ').reshape(-1, 3)*2.54
            indices = [int(v) for v in re.search(r'coordIndex \[ (.*?)\]', line)[1].replace(',', ' ').split()]
            face, triangles = [], []
            for i in indices:
                if i == -1:
                    triangles.extend((face[0], face[j], face[j+1]) for j in range(1, len(face)-1));face=[]
                else: face.append(i)
            assert not face
            mesh = trimesh.Trimesh(points, triangles, process=False)
        else: raise ValueError('Unsupported VRML shape')
        mesh.visual = trimesh.visual.TextureVisuals(material=trimesh.visual.material.PBRMaterial(
            baseColorFactor=[round(c*255) for c in color]+[255], metallicFactor=.25, roughnessFactor=.6))
        yield mesh


def main():
    parser = argparse.ArgumentParser();parser.add_argument('bare_board', type=Path);args=parser.parse_args()
    scene = trimesh.load(args.bare_board, force='scene')
    path = ROOT/'hw/skylark-usb/layout/placement.json'
    inputs = [path, ROOT/'hw/skylark-usb/boards/skylark-usb/skylark-usb.kicad_pcb', Path(__file__)]
    count=0
    for part in json.loads(path.read_text())['skylark-usb']['parts']:
        if part['dnp'] or not part['type'] or part['type']=='TP': continue
        kind=part['type']
        if kind.startswith('R_'): kind='R'
        if kind.startswith('C_'): kind='C1206' if '1206' in part['local_fp'] else 'C0805' if '0805' in part['local_fp'] else 'C0603'
        model=ROOT/f'hw/skylark-usb/models/{kind}.wrl';inputs.append(model)
        assert part['side'] in ('front','back')
        angle=math.radians(part['angle']);c,s=math.cos(angle),math.sin(angle)
        # VRML mm, Z up -> KiCad GLB metres, Y up. Front surface is at 1.6 mm.
        transform=np.array([[c,-s,0,50+part['xy'][0]], [0,0,1,1.6], [-s,-c,0,50+part['xy'][1]], [0,0,0,1000]],dtype=float)/1000
        if part['side']=='back':
            # Current rear models are symmetric package envelopes; flip the
            # local X/Z axes and place them below the board's zero surface.
            transform[:,0]*=-1;transform[:,2]*=-1;transform[1,3]=0
        for index, mesh in enumerate(models(model.read_text())):
            mesh.apply_transform(transform)
            scene.add_geometry(mesh, node_name=f'{part["ref"]}-{index}');count+=1
    target=ROOT/'sw/ui/assets/skylark.glb';scene.export(target)
    inputs.extend([target,ROOT/'sw/ui/skylark_scene.py'])
    provenance=dict(kicad='9.0.9', converter=f'trimesh {trimesh.__version__} / numpy {np.__version__}',
        scope='Native PCB plus authored dimension envelopes. PMS5003 is illustrative; enclosure and mating are not qualified.',
        package_meshes=count, sha256={p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(set(inputs))})
    (target.parent/'skylark-provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
    print(f'Exported {count} package meshes; bounds {scene.bounds.tolist()}')


if __name__=='__main__':main()
