"""Frozen shared-sensor pin fixture; independent of current placement and compiled CAD."""
EXPECTED = {'U11': {'1': 'SPI_MISO',
         '2': 'GND',
         '3': 'GND',
         '4': 'IMU1_INT',
         '5': 'SENS_3V3',
         '6': 'GND',
         '7': 'GND',
         '8': 'SENS_3V3',
         '12': 'IMU1_CS',
         '13': 'SPI_SCLK',
         '14': 'SPI_MOSI'},
 'U12': {'1': 'SPI_MISO',
         '2': 'GND',
         '3': 'GND',
         '4': 'IMU2_INT',
         '5': 'SENS_3V3',
         '6': 'GND',
         '7': 'GND',
         '8': 'SENS_3V3',
         '12': 'IMU2_CS',
         '13': 'SPI_SCLK',
         '14': 'SPI_MOSI'},
 'U13': {'1': 'SPI_MISO',
         '2': 'GND',
         '3': 'GND',
         '4': 'IMU3_INT',
         '5': 'SENS_3V3',
         '6': 'GND',
         '7': 'GND',
         '8': 'SENS_3V3',
         '12': 'IMU3_CS',
         '13': 'SPI_SCLK',
         '14': 'SPI_MOSI'},
 'U40': {'1': 'GND', '2': 'SENS_3V3', '3': 'PI_5V'},
 'U41': {'1': 'PI_3V3',
         '2': 'PI_3V3',
         '3': 'PI_SPI_MOSI',
         '4': 'PI_SPI_SCLK',
         '5': 'PI_IMU1_CS',
         '6': 'PI_IMU2_CS',
         '7': 'PI_IMU3_CS',
         '10': 'GND',
         '11': 'GND',
         '12': 'GND',
         '13': 'GND',
         '17': 'IMU3_CS',
         '18': 'IMU2_CS',
         '19': 'IMU1_CS',
         '20': 'SPI_SCLK',
         '21': 'SPI_MOSI',
         '22': 'SENSOR_OE_N',
         '23': 'SENS_3V3',
         '24': 'SENS_3V3'},
 'U42': {'1': 'PI_3V3',
         '2': 'GND',
         '3': 'PI_SPI_MISO',
         '4': 'PI_IMU1_INT',
         '5': 'PI_IMU2_INT',
         '6': 'PI_IMU3_INT',
         '11': 'GND',
         '12': 'GND',
         '13': 'GND',
         '14': 'GND',
         '15': 'GND',
         '18': 'IMU3_INT',
         '19': 'IMU2_INT',
         '20': 'IMU1_INT',
         '21': 'SPI_MISO',
         '22': 'SENSOR_OE_N',
         '23': 'SENS_3V3',
         '24': 'SENS_3V3'}}

def verify(pins):
    for ref, mapping in EXPECTED.items():
        for pin, net in mapping.items():
            assert pins.get((ref, pin)) == net, (ref, pin, net, pins.get((ref, pin)))
    return sum(map(len, EXPECTED.values()))
